# Generated by Django 4.2.2 on 2023-07-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='rank.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='rank.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
